In [1]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [2]:
model  = Sequential()

In [3]:
model.add(SimpleRNN(3,input_shape = (4,5)))
model.add(Dense(1,activation="sigmoid"))
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
model.get_weights()[0]

array([[-0.09742123, -0.79556406, -0.0285551 ],
       [-0.01822567,  0.8021665 , -0.37791917],
       [ 0.5446721 , -0.38408953, -0.72181225],
       [-0.72921014, -0.45413113,  0.1700334 ],
       [ 0.30468684, -0.66580427,  0.5595847 ]], dtype=float32)

In [5]:
from keras.datasets import imdb

In [6]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 2s 0us/step


In [7]:
X_train.shape

(25000,)

In [8]:
import numpy as np
sent = [
    "india loss worldcup",
    "virat played very well",
    "yash is good boy",
    "bharat mata ki jay",
    "dj wale babu mera gana chala do"
]

In [9]:
# it is performing integer encoding
from keras.preprocessing.text import Tokenizer
tokens = Tokenizer()

In [10]:
tokens.fit_on_texts(sent)

In [11]:
tokens.word_index

{'india': 1,
 'loss': 2,
 'worldcup': 3,
 'virat': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'yash': 8,
 'is': 9,
 'good': 10,
 'boy': 11,
 'bharat': 12,
 'mata': 13,
 'ki': 14,
 'jay': 15,
 'dj': 16,
 'wale': 17,
 'babu': 18,
 'mera': 19,
 'gana': 20,
 'chala': 21,
 'do': 22}

In [12]:
tokens.word_counts

OrderedDict([('india', 1),
             ('loss', 1),
             ('worldcup', 1),
             ('virat', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('yash', 1),
             ('is', 1),
             ('good', 1),
             ('boy', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('dj', 1),
             ('wale', 1),
             ('babu', 1),
             ('mera', 1),
             ('gana', 1),
             ('chala', 1),
             ('do', 1)])

In [13]:
tokens.document_count

5

In [14]:
encoding = tokens.texts_to_sequences(sent)

In [15]:
encoding

[[1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19, 20, 21, 22]]

In [16]:
from keras.utils import pad_sequences
pad_sequences(encoding)

array([[ 0,  0,  0,  0,  1,  2,  3],
       [ 0,  0,  0,  4,  5,  6,  7],
       [ 0,  0,  0,  8,  9, 10, 11],
       [ 0,  0,  0, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22]], dtype=int32)

In [17]:
pad_sequences(encoding,padding="post")

array([[ 1,  2,  3,  0,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0,  0],
       [ 8,  9, 10, 11,  0,  0,  0],
       [12, 13, 14, 15,  0,  0,  0],
       [16, 17, 18, 19, 20, 21, 22]], dtype=int32)

In [18]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [19]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [21]:
X_train = pad_sequences(X_train,padding="post",maxlen=100)

In [22]:
X_test = pad_sequences(X_test,padding="post",maxlen=100)

In [24]:
model = Sequential()

In [25]:
model.add(SimpleRNN(32,input_shape=(100,1)))

In [26]:
model.add(Dense(1,activation="sigmoid"))

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [34]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=8,batch_size=42)

Epoch 1/8
596/596 [==============================] - 45s 76ms/step - loss: 0.6928 - accuracy: 0.5100 - val_loss: 0.6940 - val_accuracy: 0.5074
Epoch 2/8
596/596 [==============================] - 41s 69ms/step - loss: 0.6926 - accuracy: 0.5153 - val_loss: 0.6931 - val_accuracy: 0.5049
Epoch 3/8
596/596 [==============================] - 41s 68ms/step - loss: 0.6926 - accuracy: 0.5101 - val_loss: 0.6932 - val_accuracy: 0.5082
Epoch 4/8
596/596 [==============================] - 41s 68ms/step - loss: 0.6928 - accuracy: 0.5090 - val_loss: 0.6923 - val_accuracy: 0.5106
Epoch 5/8
596/596 [==============================] - 41s 69ms/step - loss: 0.6924 - accuracy: 0.5100 - val_loss: 0.6936 - val_accuracy: 0.5110
Epoch 6/8
596/596 [==============================] - 41s 69ms/step - loss: 0.6923 - accuracy: 0.5133 - val_loss: 0.6924 - val_accuracy: 0.5132
Epoch 7/8
596/596 [==============================] - 41s 68ms/step - loss: 0.6926 - accuracy: 0.5103 - val_loss: 0.6925 - val_accuracy: 0.5071

In [35]:
model.predict(X_test)

782/782 [==============================] - 9s 11ms/step


array([[0.53485584],
       [0.49233946],
       [0.49233946],
       ...,
       [0.53368515],
       [0.41250676],
       [0.49233946]], dtype=float32)

In [36]:
model.evaluate(X_test,y_test)

782/782 [==============================] - 7s 9ms/step - loss: 0.6924 - accuracy: 0.5126


[0.6924281120300293, 0.5126000046730042]