In [1]:
import pandas as pd
import numpy as np
import os 

# BAG OF WORDS

In [2]:
df = pd.DataFrame({"text":["people watch yash","yash watch yash","yash write comment","people write comment"],"output":[1,1,0,0]})

In [3]:
df

text  output
0     people watch yash       1
1       yash watch yash       1
2    yash write comment       0
3  people write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df["text"])

In [6]:
print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'yash': 4, 'write': 3, 'comment': 0}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 1]]
[[0 0 1 0 2]]


# one hot encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()
one = onehot.fit_transform(df[["text"]])

In [9]:
print(one[0].toarray())
print(one[1].toarray())
print(one[2].toarray())

[[1. 0. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 0. 1.]]


# N-grams

In [21]:
n = CountVectorizer(ngram_range=(2,2))

In [22]:
ngram = n.fit_transform(df["text"])

In [23]:
print(n.vocabulary_)

{'people watch': 0, 'watch yash': 2, 'yash watch': 4, 'yash write': 5, 'write comment': 3, 'people write': 1}


In [24]:
print(ngram[0].toarray())
print(ngram[1].toarray())

[[1 0 1 0 0 0]]
[[0 0 1 0 1 0]]


# TF-IDF

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [26]:
tfidf = tfidf.fit_transform(df["text"])

In [29]:
tfidf.toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ]])